// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irmkughpzzecpacaikjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlybWt1Z2hwenplY3BhY2Fpa2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjQyMDUsImV4cCI6MjA2NTMwMDIwNX0.FxXEF_d2vL-CBPsKeptJfs9DPawixalprNu0GTOOvPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);